export const SCENE_TYPES = [
  { value: 'urban', label: 'Urbano' },
  { value: 'interior', label: 'Interior' },
  { value: 'vegetation', label: 'Vegetación' },
  { value: 'riverbank', label: 'Ribera' },
  { value: 'general', label: 'General' },
];

export const TEXTURE_MODES = [
  { value: 'dots', label: 'Puntos' },
  { value: 'lines', label: 'Líneas' },
  { value: 'cross', label: 'Trama cruzada' },
  { value: 'organic', label: 'Orgánica' },
  { value: 'concrete', label: 'Grano concreto' },
  { value: 'foliage', label: 'Masa vegetal' },
  { value: 'none', label: 'Sin trama' },
];

export const EXPORT_FORMATS = [
  { value: 'web', label: 'Web 2000px', px: 2000, inches: 6.67 },
  { value: 'a5-300', label: 'A5 · 300dpi', px: 2480, inches: 8.27, dpi: 300, page: 'A5' },
  { value: 'a5-450', label: 'A5 · 450dpi', px: 3720, inches: 8.27, dpi: 450, page: 'A5' },
  { value: 'a5-600', label: 'A5 · 600dpi · alta resolución', px: 4960, inches: 8.27, dpi: 600, page: 'A5', highResolution: true },
  { value: 'a4-300', label: 'A4 · 300dpi', px: 3508, inches: 11.69, dpi: 300, page: 'A4' },
  { value: 'a4-450', label: 'A4 · 450dpi', px: 5261, inches: 11.69, dpi: 450, page: 'A4' },
  { value: 'a4-600', label: 'A4 · 600dpi · alta resolución', px: 7014, inches: 11.69, dpi: 600, page: 'A4', highResolution: true },
];

export const CONTROL_DEFS = {
  value: { label: 'Valor', min: -60, max: 60, step: 1 },
  brightness: { label: 'Brillo', min: -80, max: 80, step: 1 },
  contrast: { label: 'Contraste', min: -60, max: 80, step: 1 },
  blackPoint: { label: 'Punto negro', min: 0, max: 100, step: 1 },
  whitePoint: { label: 'Punto blanco', min: 155, max: 255, step: 1 },
  gamma: { label: 'Gamma / medios tonos', min: 40, max: 240, step: 1 },
  grayscaleMix: { label: 'Mezcla blanco y negro', min: 0, max: 100, step: 1 },
  detail: { label: 'Detalle', min: 0, max: 100, step: 1 },
  cleanup: { label: 'Limpieza', min: 0, max: 100, step: 1 },
  lineSimplify: { label: 'Simplificación', min: 0, max: 100, step: 1 },
  lineConnect: { label: 'Conectar líneas', min: 0, max: 100, step: 1 },
  mainLine: { label: 'Intensidad línea principal', min: 0, max: 100, step: 1 },
  mainLineWeight: { label: 'Grosor línea principal', min: 0, max: 6, step: 1 },
  secondaryLine: { label: 'Intensidad línea secundaria', min: 0, max: 100, step: 1 },
  secondaryLineWeight: { label: 'Grosor línea secundaria', min: 0, max: 4, step: 1 },
  fineDetail: { label: 'Detalle fino', min: 0, max: 100, step: 1 },
  fineDetailWeight: { label: 'Grosor detalle fino', min: 0, max: 3, step: 1 },
  edgeContinuity: { label: 'Continuidad de contornos', min: 0, max: 100, step: 1 },
  farDetail: { label: 'Detalle lejano', min: 0, max: 100, step: 1 },
  whiteReserve: { label: 'Reserva de blanco', min: 0, max: 80, step: 1 },
  blackMass: { label: 'Masas negras', min: 0, max: 100, step: 1 },
  blackCoverageLimit: { label: 'Cobertura de negro', min: 0, max: 55, step: 1 },
  shadowThreshold: { label: 'Umbral de sombra', min: 0, max: 100, step: 1 },
  toneSoftness: { label: 'Suavidad tonal', min: 0, max: 100, step: 1 },
  toneCount: { label: 'Cantidad de tonos', min: 3, max: 5, step: 1 },
  transitionHardness: { label: 'Dureza tonal', min: 0, max: 100, step: 1 },
  texture: { label: 'Textura', min: 0, max: 100, step: 1 },
  posterization: { label: 'Posterización', min: 0, max: 100, step: 1 },
  thresholdMix: { label: 'Threshold', min: 0, max: 100, step: 1 },
  shadowCompression: { label: 'Compresión de negros', min: 0, max: 100, step: 1 },
  regionMerge: { label: 'Fusión de regiones pequeñas', min: 0, max: 100, step: 1 },
  skyInfluence: { label: 'Influencia cielo', min: 0, max: 100, step: 1 },
  architectureInfluence: { label: 'Influencia arquitectura', min: 0, max: 100, step: 1 },
  waterInfluence: { label: 'Influencia agua', min: 0, max: 100, step: 1 },
  vegetationInfluence: { label: 'Influencia vegetación', min: 0, max: 100, step: 1 },
  perspectiveStrength: { label: 'Preservación geométrica', min: 0, max: 100, step: 1 },
};

export const DEFAULT_SETTINGS = {
  preset: 'staged-drawing',
  sceneType: 'urban',
  exportFormat: 'web',
  textureMode: 'none',
  value: 14,
  brightness: 10,
  contrast: 12,
  blackPoint: 8,
  whitePoint: 246,
  gamma: 112,
  grayscaleMix: 100,
  detail: 64,
  cleanup: 62,
  lineSimplify: 56,
  lineConnect: 62,
  mainLine: 72,
  mainLineWeight: 2,
  secondaryLine: 68,
  secondaryLineWeight: 1,
  fineDetail: 42,
  fineDetailWeight: 0,
  edgeContinuity: 64,
  farDetail: 34,
  whiteReserve: 62,
  blackMass: 12,
  blackCoverageLimit: 8,
  shadowThreshold: 42,
  toneSoftness: 62,
  toneCount: 4,
  transitionHardness: 34,
  texture: 8,
  posterization: 18,
  thresholdMix: 6,
  shadowCompression: 72,
  regionMerge: 52,
  skyInfluence: 90,
  architectureInfluence: 88,
  waterInfluence: 82,
  vegetationInfluence: 62,
  perspectiveStrength: 78,
  depthEnabled: true,
  skyProtect: true,
  architectureBoost: true,
  organicRegions: true,
  waterClean: true,
  preserveLightTrails: true,
  showMainLine: true,
  showSecondaryLine: true,
  showFineDetail: true,
  blueSketch: false,
  grayscaleEnabled: true,
  shadowsEnabled: true,
  vegetationEnabled: true,
  lightsEnabled: true,
};

export const PRESETS = [
  {
    id: 'staged-drawing',
    name: 'Flujo tipo Clip Studio',
    settings: {
      sceneType: 'urban', textureMode: 'none', value: 12, brightness: 8, contrast: 12,
      blackPoint: 7, whitePoint: 247, gamma: 112, grayscaleMix: 100,
      detail: 66, cleanup: 68, lineSimplify: 58, lineConnect: 68,
      mainLine: 78, mainLineWeight: 2, secondaryLine: 74, secondaryLineWeight: 1,
      fineDetail: 38, fineDetailWeight: 0, edgeContinuity: 72, farDetail: 34,
      whiteReserve: 70, blackMass: 7, blackCoverageLimit: 4, shadowThreshold: 42,
      toneSoftness: 78, toneCount: 4, transitionHardness: 22, texture: 0,
      posterization: 12, thresholdMix: 3, shadowCompression: 78, regionMerge: 58,
      skyInfluence: 94, architectureInfluence: 92, waterInfluence: 88,
      vegetationInfluence: 58, perspectiveStrength: 86, depthEnabled: true,
      skyProtect: true, architectureBoost: true, organicRegions: true, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false, grayscaleEnabled: true,
      shadowsEnabled: true, vegetationEnabled: true, lightsEnabled: true,
    },
  },
  {
    id: 'inking-base',
    name: 'Base para entintado',
    settings: {
      sceneType: 'urban', textureMode: 'none', value: 18, brightness: 14, contrast: 8,
      blackPoint: 5, whitePoint: 250, gamma: 118, grayscaleMix: 100,
      detail: 66, cleanup: 72, lineSimplify: 64, lineConnect: 72, mainLine: 78, mainLineWeight: 2,
      secondaryLine: 72, secondaryLineWeight: 1, fineDetail: 38, fineDetailWeight: 0,
      edgeContinuity: 70, farDetail: 30, whiteReserve: 68, blackMass: 8,
      blackCoverageLimit: 5, shadowThreshold: 36, toneSoftness: 74, toneCount: 4,
      transitionHardness: 18, texture: 0, posterization: 6, thresholdMix: 0,
      shadowCompression: 84, regionMerge: 66, skyInfluence: 98,
      architectureInfluence: 94, waterInfluence: 92, vegetationInfluence: 48,
      perspectiveStrength: 90, depthEnabled: true, skyProtect: true,
      architectureBoost: true, organicRegions: false, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false, grayscaleEnabled: true,
      shadowsEnabled: true, vegetationEnabled: true, lightsEnabled: true,
    },
  },
  {
    id: 'urban-clean',
    name: 'Urbano limpio',
    settings: {
      sceneType: 'urban', textureMode: 'lines', value: 12, brightness: 8, contrast: 16,
      detail: 56, cleanup: 72, mainLine: 70, mainLineWeight: 2,
      secondaryLine: 62, secondaryLineWeight: 1, fineDetail: 24, fineDetailWeight: 0,
      edgeContinuity: 66, farDetail: 24, whiteReserve: 62, blackMass: 16,
      blackCoverageLimit: 8, shadowThreshold: 50, toneSoftness: 66, toneCount: 4,
      transitionHardness: 40, texture: 12, depthEnabled: true, skyProtect: true,
      architectureBoost: true, organicRegions: false, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false,
    },
  },
  {
    id: 'urban-dramatic',
    name: 'Urbano dramático',
    settings: {
      sceneType: 'urban', textureMode: 'cross', value: 0, brightness: 0, contrast: 24,
      detail: 66, cleanup: 54, mainLine: 82, mainLineWeight: 3,
      secondaryLine: 58, secondaryLineWeight: 1, fineDetail: 32, fineDetailWeight: 0,
      edgeContinuity: 72, farDetail: 32, whiteReserve: 44, blackMass: 44,
      blackCoverageLimit: 22, shadowThreshold: 38, toneSoftness: 42, toneCount: 4,
      transitionHardness: 62, texture: 24, depthEnabled: true, skyProtect: true,
      architectureBoost: true, organicRegions: false, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false,
    },
  },
  {
    id: 'seinen-detail',
    name: 'Seinen detallado',
    settings: {
      sceneType: 'urban', textureMode: 'dots', value: 6, brightness: 4, contrast: 18,
      detail: 82, cleanup: 44, mainLine: 66, mainLineWeight: 1,
      secondaryLine: 78, secondaryLineWeight: 1, fineDetail: 64, fineDetailWeight: 0,
      edgeContinuity: 58, farDetail: 42, whiteReserve: 46, blackMass: 24,
      blackCoverageLimit: 12, shadowThreshold: 46, toneSoftness: 58, toneCount: 5,
      transitionHardness: 42, texture: 34, depthEnabled: true, skyProtect: true,
      architectureBoost: true, organicRegions: true, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false,
    },
  },
  {
    id: 'vegetation-manga',
    name: 'Vegetación manga',
    settings: {
      sceneType: 'vegetation', textureMode: 'foliage', value: -4, brightness: 2, contrast: 12,
      detail: 70, cleanup: 36, mainLine: 60, mainLineWeight: 2,
      secondaryLine: 56, secondaryLineWeight: 1, fineDetail: 48, fineDetailWeight: 0,
      edgeContinuity: 38, farDetail: 38, whiteReserve: 34, blackMass: 50,
      blackCoverageLimit: 22, shadowThreshold: 44, toneSoftness: 46, toneCount: 4,
      transitionHardness: 42, texture: 70, depthEnabled: true, skyProtect: false,
      architectureBoost: false, organicRegions: true, waterClean: false,
      preserveLightTrails: false, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false,
    },
  },
  {
    id: 'riverbank',
    name: 'Ribera',
    settings: {
      sceneType: 'riverbank', textureMode: 'organic', value: 10, brightness: 8, contrast: 10,
      detail: 56, cleanup: 62, mainLine: 62, mainLineWeight: 2,
      secondaryLine: 54, secondaryLineWeight: 1, fineDetail: 24, fineDetailWeight: 0,
      edgeContinuity: 44, farDetail: 30, whiteReserve: 60, blackMass: 30,
      blackCoverageLimit: 14, shadowThreshold: 50, toneSoftness: 64, toneCount: 4,
      transitionHardness: 34, texture: 30, depthEnabled: true, skyProtect: true,
      architectureBoost: false, organicRegions: true, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: false,
    },
  },
  {
    id: 'blue-sketch',
    name: 'Boceto azul',
    settings: {
      sceneType: 'general', textureMode: 'none', value: 18, brightness: 12, contrast: 8,
      detail: 74, cleanup: 62, mainLine: 74, mainLineWeight: 1,
      secondaryLine: 70, secondaryLineWeight: 0, fineDetail: 36, fineDetailWeight: 0,
      edgeContinuity: 48, farDetail: 42, whiteReserve: 76, blackMass: 0,
      blackCoverageLimit: 0, shadowThreshold: 70, toneSoftness: 70, toneCount: 3,
      transitionHardness: 22, texture: 0, depthEnabled: true, skyProtect: true,
      architectureBoost: true, organicRegions: false, waterClean: true,
      preserveLightTrails: true, showMainLine: true, showSecondaryLine: true,
      showFineDetail: true, blueSketch: true,
    },
  },
];
